import 'package:catalog_city_project/util/string_config.dart';

final Map<String, String> frFR = {
  StringConfig.appName: 'Catalog City',
  StringConfig.peopleDonTakeTripsTripsTakePeople:
      'Les gens ne prennent pas de voyages, les voyages prennent les gens',
  StringConfig.lifeSsShortAndTheWorldIsWide:
      'La vie est courte et le monde est vaste',
  StringConfig.getReadyForYourLifetimeJourney:
      'Préparez-vous pour votre voyage de vie',
  StringConfig.skip: 'Passer',
  StringConfig.primeTravelApp: 'P r i m e  A p p  d e  V o y a g e',
  StringConfig.next: 'Suivant',
  StringConfig.start: 'Commencer',
  StringConfig.editProfile: 'Modifier le profil',
  StringConfig.edit: 'Modifier',
  StringConfig.saveDetails: 'Enregistrer les détails',
  StringConfig.mobileNumber: 'Numéro de mobile',
  StringConfig.email: 'E-mail',
  StringConfig.welcomeBack: "Bienvenue",
  StringConfig.getStarted: 'Commencer',
  StringConfig.enterPassword: 'Entrez le mot de passe',
  StringConfig.enterConfirmPassword: 'Entrez le mot de passe de confirmation',
  StringConfig.enterEmail: 'Entrez l\'e-mail',
  StringConfig.enterName: 'Entrez le nom',
  StringConfig.forgotPasswordQ: 'Mot de passe oublié?',
  StringConfig.forgotPassword: 'Mot de passe oublié',
  StringConfig.orContinueWith: 'Ou continuer avec',
  StringConfig.logIn: "Se connecter",
  StringConfig.thisFieldIsRequired: "Ce champ est requis",
  StringConfig.invalidEmail: "E-mail invalide",
  StringConfig.google: "Google",
  StringConfig.facebook: "Facebook",
  StringConfig.donTHaveAnAccount: "Vous n'avez pas de compte?",
  StringConfig.signUp: "S'inscrire",
  StringConfig.passwordNotMatch:
      "Le mot de passe et la confirmation ne correspondent pas.",
  StringConfig.createANewAccount: "Créer un nouveau compte",
  StringConfig.createNewAccount: "Créer un nouveau mot de passe",
  StringConfig.pleaseEnterYourDetails: 'Veuillez entrer vos détails',
  StringConfig.alreadyAMember: 'Déjà membre?',
  StringConfig.oTPVerification: 'Vérification OTP',
  StringConfig.verify: 'Vérifier',
  StringConfig.resendCodeIn: 'Renvoyer le code dans',
  StringConfig.resendCode: 'Renvoyer le code?',
  StringConfig.double25: '00:25',
  StringConfig.home: 'Accueil',
  StringConfig.myTrip: 'Mon voyage',
  StringConfig.myBooking: 'Mes réservations',
  StringConfig.selectDeparture: 'Sélectionner le départ',
  StringConfig.selectDestination: 'Sélectionner la destination',
  StringConfig.myReviews: 'Mes avis',
  StringConfig.myFavorite: 'Mes favoris',
  StringConfig.favorite: 'Favoris',
  StringConfig.myProfile: 'Mon profil',
  StringConfig.offers: 'Offres',
  StringConfig.english: 'Anglais',
  StringConfig.hindi: 'Hindi',
  StringConfig.german: 'Allemand',
  StringConfig.french: 'Français',
  StringConfig.arabic: 'Arabe',
  StringConfig.chinese: 'Chinois',
  StringConfig.settings: 'Paramètres',
  StringConfig.logOut: 'Déconnexion',
  StringConfig.yes: 'Oui',
  StringConfig.areYouSureYouWantToLogOut:
      'Êtes-vous sûr de vouloir vous déconnecter?',
  StringConfig.janeCooper: 'salma taoussi',
  StringConfig.searchPlaces: 'Pays, villes, activités',
  StringConfig.search: 'Recherche',
  StringConfig.economyBasicEconomySaver: 'Économie de base / Économie',
  StringConfig.fareOfferedByAirline: 'Tarif offert par la compagnie aérienne',
  StringConfig.restau: 'Restaurants',
  StringConfig.activ: 'Activités',
  StringConfig.hotel0: 'Hôtels',
  StringConfig.cabinBag: 'Bagage cabine',
  StringConfig.checkIn: 'Enregistrement',
  StringConfig.w8kgs: '8Kgs',
  StringConfig.w25kgs: '25Kgs',
  StringConfig.cancellationFeeStarting:
      'Frais d\'annulation à partir de\n\$450',
  StringConfig.dateChangesFeeStarting:
      'Frais de changement de date à partir de\n\$350',
  StringConfig.$450: '\$450',
  StringConfig.$350: '\$350',
  StringConfig.$2860: '\$2,860',
  StringConfig.$2860_20: '\$2,860.20',
  StringConfig.$8812: ' \$88.12',
  StringConfig.$0: '\$0',
  StringConfig.$100_25: ' \$100.25',
  StringConfig.cancellation: 'Annulation',
  StringConfig.dateChanges: 'Changements de date',
  StringConfig.popularPlaces: 'Lieux populaires',
  StringConfig.mussoorie: 'Mussoorie',
  StringConfig.yamunotri: 'Yamunotri',
  StringConfig.losAngeles: 'Los Angeles',
  StringConfig.hogsFeet: 'Hogsfeet',
  StringConfig.chester: 'Chester',
  StringConfig.craft: 'magasins d\'artisanat',
  StringConfig.send: 'Envoyer',
  StringConfig.reset: 'Réinitialiser',
  StringConfig.casablanca: 'Casablanca', //
  StringConfig.agadir: 'Agadir',
  StringConfig.marrakech: 'Marrakech',
  StringConfig.tanger: 'Tanger',
  StringConfig.ouarzazat: 'Ouarzazat',
  StringConfig.essaouira: 'Essaouira',
  StringConfig.southeastAsiaEast: 'Asie du Sud-Est, Est',
  StringConfig.agadirLoc: 'Sud du Maroc',
  StringConfig.casablancaLoc: 'Nord du Maroc',
  StringConfig.internationalTrip: 'Voyage international',
  StringConfig.seeMore: 'Voir plus',
  StringConfig.vietnam: 'Vietnam',
  StringConfig.hoChiMinhCity: 'Ho Chi Minh-Ville',
  StringConfig.srinagar: 'Srinagar',
  StringConfig.manali: 'Manali',
  StringConfig.rishikesh: 'Rishikesh',
  StringConfig.darjeeling: 'Darjeeling',
  StringConfig.night6Days: '5 Nuits/6 Jours',
  StringConfig.srinagar1N: 'Srinagar(1N)',
  StringConfig.gulmarg1N: 'Gulmarg(1N)',
  StringConfig.pahalgam1N: 'Pahalgam(1N)',
  StringConfig.srinagar2N: 'Srinagar(2N)',
  StringConfig.twinSharingRooms: 'Chambres doubles',
  StringConfig.privateCabWithDriver: 'Taxi privé avec chauffeur',
  StringConfig.sightseeingCab: 'Taxi touristique',
  StringConfig.breakfastDinner: 'Petit-déjeuner, Dîner',
  StringConfig.bookNow: 'Réservez maintenant',
  StringConfig.anitejaNigam: 'Aniteja Nigam',
  StringConfig.atreNisheeth: 'Atre Nisheeth',
  StringConfig.udarSahar: 'Udar Sahar',
  StringConfig.neelmaniRupali: 'Neelmani Rupali',
  StringConfig.mohalGiridharan: 'Mohal Giridharan',
  StringConfig.picturesqueHon: 'Tour Hassan', //
  StringConfig.picturesqueHoneymoonSrinagar:
      'Lune de miel pittoresque - Srinagar...',
  StringConfig.loremIpsumDolorSitAmet: 'Lorem ipsum dolor sit amet',
  StringConfig.dateOfTravelGuests: 'Date de voyage et invités',
  StringConfig.tourItinerary: 'Itinéraire du tour',
  StringConfig.raisonHotel: 'Hôtel Raison',
  StringConfig.amenities: 'Commodités',
  StringConfig.package: 'Forfaits',
  StringConfig.popularHotels: 'Hôtels populaires',
  StringConfig.viewDetails: 'Voir les détails',
  StringConfig.reviewer: 'Avis',
  StringConfig.toDay: 'Aujourd\'hui',
  StringConfig.languages: 'Langues',
  StringConfig.goodHotelWorthEveryPenny: 'Bon hôtel, vaut chaque centime !!',
  StringConfig.wadeWarren: 'Wade Warren',
  StringConfig.ralphEdwards: 'Ralph Edwards',
  StringConfig.devonLane: 'Devon Lane',
  StringConfig.yesterday: 'Hier',
  StringConfig.wiFi: "Wi-Fi",
  StringConfig.bar: "Bar",
  StringConfig.breakFast: "Petit déjeuner",
  StringConfig.pool: "Piscine",
  StringConfig.all: "Tout",
  StringConfig.off14: "14% de réduction",
  StringConfig.room1: "1 chambre",
  StringConfig.guests1: "1 invité",
  StringConfig.reviewer120: "( 120 avis )",
  StringConfig.southeast: "Sud-Est",
  StringConfig.southeastAsiaFarEast: "Asie du Sud-Est, Extrême\nOrient",
  StringConfig.checkIn2PM: 'Enregistrement\n2 PM',
  StringConfig.viewOnMap: 'Voir sur la carte',
  StringConfig.help: 'Aider',
  StringConfig.termsAndConditions: 'Conditions générales',
  StringConfig.privacyAndPolicy: 'Vie privée et politique',
  StringConfig.showMore: 'voir plus',
  StringConfig.showLess: 'voir moins',
  StringConfig.person: 'Personne',
  StringConfig.noTourSavedYet: 'Rien n\'est encore sauvegardé',
  StringConfig.saveOrganizeAndShareActivesAndTour:
      'Sauvegarder, organiser et partager des activités',
  StringConfig.findNewActivities: 'En savoir plus'
};
