name: catalog_city_project
description: Cataloge city project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
# Flutter version: 3.16.3
# Dart version: 3.2.3
version: 1.0.2

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  pinput: ^2.2.31
  persistent_bottom_nav_bar: ^5.0.2
  cloudinary: ^1.2.0
  flutter_switch: ^0.3.2
  syncfusion_flutter_datepicker: "24.2.6"
  map_launcher: ^2.5.0+1
  readmore: ^3.0.0
  video_player: ^2.2.18
  path_provider: ^2.1.3
  intl: any
  share_plus: ^7.0.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^0.8.7+5
  shared_preferences: ^2.2.2
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/dev/

  fonts:
    - family: Satoshi_Regular
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
    - family: Satoshi_Medium
      fonts:
        - asset: assets/fonts/Satoshi-Medium.otf
    - family: Satoshi_Bold
      fonts:
        - asset: assets/fonts/Satoshi-Bold.otf
    - family: Satoshi_Italic
      fonts:
        - asset: assets/fonts/Satoshi-Italic.otf
    - family: Satoshi_light
      fonts:
        - asset: assets/fonts/Satoshi-Light.otf
